---
swagger: "2.0"

info:
  version: "1.0.0"

basePath: /dev

schemes:
  - https

consumes:
  - application/json

produces:
  - application/json

paths:
  /posts:
    get:
      description: posts handler
      operationId: posts-handler
  /webhook:
    post:
      description: webhook handler
      operationId: webhook-handler