---
swagger: "2.0"

info:
  version: "1.0.0"

basePath: /dev

schemes:
  - https

consumes:
  - application/json

produces:
  - application/json

paths:
  /graphql:
    get:
      description: graphql handler
      operationId: graphql-handler